apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-viewer
rules:
- apiGroups: [ "", "apps", "batch", "extensions" ]
  resources: [ "pods", "pods/log", "services", "deployments", "replicasets", "jobs", "cronjobs", "daemonsets", "statefulsets", "namespaces", "nodes", "persistentvolumes", "configmaps", "persistentvolumeclaims" ]
  verbs: [ "get", "list", "watch" ]
